dataset:
  name: brain
  num_workers: 0 # default 0 because we do not use large batch size with 3D model and volumes anyways
  data_dir: '/home/moucheng/projects_data/Task01_BrainTumour'
  data_format: 'nii'

logger:
  tag: 'cluster_brain'

seed: 1024

model:
  input_dim: 4
  output_dim: 1
  width: 10
  depth: 3

train:
  transpose_dim: 1
  optimizer:
    weight_decay: 0.0005
  lr: 0.001
  iterations: 10000
  batch: 2
  temp: 1.0
  contrast: False
  crop_aug: True
  gaussian: False
  new_size_d: 32
  new_size_w: 96
  new_size_h: 96
  batch_u: 1 # this has to be zero in supervised setting
  mu: 0.5
  learn_threshold: 1 # 0 for using fixed mu, 1 for using mu as a prior
  threshold_flag: 1 # 0 for the original implementation, 1 for new lazy implementation
  alpha: 1.0
  warmup: 0.1
  warmup_start: 0.1

checkpoint:
  resume: False
  checkpoint_path: '/some/path/to/saved/model'







