dataset:
  name: lungcancer
  num_workers: 0 # default 0 because we do not use large batch size with 3D model and volumes anyways
  data_dir: '/SAN/medic/PerceptronHead/data/Task06_Lung'
  data_format: 'nii'

logger:
  tag: 'cluster_lung'

seed: 1024

model:
  input_dim: 1
  output_dim: 1
  width: 6
  depth: 3

train:
  transpose_dim: 1
  optimizer:
    weight_decay: 0.0005
  lr: 0.01
  iterations: 20000
  batch: 1
  temp: 1.0
  contrast: False
  crop_aug: True
  gaussian: False
  new_size_d: 8
  new_size_w: 448
  new_size_h: 448
  batch_u: 1 # this has to be zero in supervised setting
  mu: 0.5
  learn_threshold: 1 # 0 for using fixed mu, 1 for using mu as a prior
  threshold_flag: 0 # 0 for the original implementation, 1 for new lazy implementation
  alpha: 1.0
  warmup: 0.1
  warmup_start: 0.05

checkpoint:
  resume: False
  checkpoint_path: '/some/path/to/saved/model'







